### ISSUE TITLE
ReferenceError: URL is not defined at t.fetchRequest

### ISSUE THREAD

**Issue by AniX** [vhx/vhx-js#11]
I'm receiving this error when trying to issue a request to VHX API (analytics). I've tried to transfer the example in the Readme of the new `vhx-js` to the samples shown in the API docs (for the previous JS client), but I'm not sure whether I misunderstood the docs or it's a bug.

Environment: Node.js 6 (Google Cloud Functions)

**package.json**

```json
{
  "name": "sample-http",
  "version": "0.0.1",
  "dependencies": {
    "@vhx/vhxjs": "^3.0.0"
  }
}
```

**index.js**
```javascript
exports.main = (req, res) => {
  const VhxApi = require('@vhx/vhxjs/dist/index.js');
  const vhx = new VhxApi('API_KEY_REDACTED');
  vhx.analytics.retrieve("https://api.vhx.tv/analytics?&type=traffic&to=today&site_id=1&from=1-month-ago&per_page=25").then(res => console.log(res)); // problem here?
  res.status(200).send('OK');
};
```

## Logged exception

```
ReferenceError: URL is not defined 
at t.fetchRequest (/user_code/node_modules/@vhx/vhxjs/dist/index.js:1:2402) 
at t.createRequestParams (/user_code/node_modules/@vhx/vhxjs/dist/index.js:1:2334) 
at t.n.(anonymous function) [as retrieve] (/user_code/node_modules/@vhx/vhxjs/dist/index.js:1:1730) 
at exports.main (/user_code/index.js:16:17) 
at /var/tmp/worker/worker.js:689:7 
at /var/tmp/worker/worker.js:673:9 
at _combinedTickCallback (internal/process/next_tick.js:73:7) 
at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Before this, I've tried a different line:
```javascript
vhx.analytics.retrieve({
  type: "traffic",
  to: "today",
  from: "1-month-ago"
}).then(res => console.log(res));
```
but have received the same error (*URL is not defined*).

**Comment by AniX** [comment]
I've noticed that there is still a separate library [`vhx`](https://www.npmjs.com/package/vhx) (1.8.0) specifically for Node.js. It seems that `@vhx/vhxjs` does not replace the old vhx for Node.js, so my issue would be invalid, I guess.
