### ISSUE TITLE
Error: Service Unavailable

### ISSUE THREAD

**Issue by jasenkoh** [vhx/vhx-js#9]
Hi,

I'm getting 503 almost constantly (`UnhandledPromiseRejectionWarning: Unhandled promise rejection`, I've contacted vhx support directly seems that there are no related logs to my requests, could id be that there's underlying issue with client?

Here's full trace:

```
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Service Unavailable
    at Request.callback (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/index.js:626:17)
    at /home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/index.js:795:18
    at IncomingMessage.<anonymous> (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  original: null,
  response: 
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: [Object],
     request: [Object],
     req: [Object],
     links: {},
     text: '{}',
     body: {},
     files: undefined,
     buffered: true,
     headers: [Object],
     header: [Object],
     statusCode: 503,
     status: 503,
     statusType: 5,
     info: false,
     ok: false,
     redirect: false,
     clientError: false,
     serverError: true,
     error: [Object],
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     type: 'application/json',
     setEncoding: [Function: bound ],
     redirects: [] },
  status: 503 } } reason: { Error: Service Unavailable
    at Request.callback (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/index.js:626:17)
    at /home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/index.js:795:18
    at IncomingMessage.<anonymous> (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  original: null,
  response: 
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 503,
        statusMessage: 'Service Unavailable',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        text: '{}',
        read: [Function],
        body: {} },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'GET',
        url: 'https://api.vhx.tv/analytics',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: [Object],
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        _withCredentials: true,
        req: [Object],
        protocol: 'https:',
        host: 'api.vhx.tv',
        _callback: [Function],
        _fullfilledPromise: [Object],
        res: [Object],
        _timeout: 0,
        response: [Circular],
        called: true },
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /analytics?type=video&video_id=225434&from=2018-01-16&by=day HTTP/1.1\r\nHost: api.vhx.tv\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/2.3.0\r\nAuthorization: Basic {MYKEY}=\r\nContent-Type: application/json\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/analytics?type=video&video_id=225434&from=2018-01-16&by=day',
        _ended: true,
        parser: null,
        res: [Object] },
     links: {},
     text: '{}',
     body: {},
     files: undefined,
     buffered: true,
     headers: 
      { server: 'Varnish',
        'retry-after': '0',
        'content-type': 'application/json',
        'content-length': '2',
        'accept-ranges': 'bytes',
        date: 'Sun, 21 Jan 2018 16:42:48 GMT',
        via: '1.1 varnish',
        connection: 'close',
        'x-served-by': 'cache-fra19141-FRA',
        'x-cache': 'MISS',
        'x-cache-hits': '0',
        'x-timer': 'S1516552968.754086,VS0,VE628',
        'access-control-allow-credentials': 'true',
        'access-control-allow-headers': 'Accept, Authorization, Content-Type',
        'access-control-allow-methods': 'HEAD, GET, PUT, POST, DELETE, OPTIONS',
        'access-control-expose-headers': 'X-User-Id, X-Ads-Enabled, X-Authorization-Token',
        'access-control-max-age': '0' },
     header: 
      { server: 'Varnish',
        'retry-after': '0',
        'content-type': 'application/json',
        'content-length': '2',
        'accept-ranges': 'bytes',
        date: 'Sun, 21 Jan 2018 16:42:48 GMT',
        via: '1.1 varnish',
        connection: 'close',
        'x-served-by': 'cache-fra19141-FRA',
        'x-cache': 'MISS',
        'x-cache-hits': '0',
        'x-timer': 'S1516552968.754086,VS0,VE628',
        'access-control-allow-credentials': 'true',
        'access-control-allow-headers': 'Accept, Authorization, Content-Type',
        'access-control-allow-methods': 'HEAD, GET, PUT, POST, DELETE, OPTIONS',
        'access-control-expose-headers': 'X-User-Id, X-Ads-Enabled, X-Authorization-Token',
        'access-control-max-age': '0' },
     statusCode: 503,
     status: 503,
     statusType: 5,
     info: false,
     ok: false,
     redirect: false,
     clientError: false,
     serverError: true,
     error: 
      { Error: cannot GET /analytics?type=video&video_id=225434&from=2018-01-16&by=day (503)
          at Response.toError (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/response.js:106:13)
          at Response._setStatusProperties (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/response.js:183:12)
          at new Response (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/response.js:42:8)
          at Request._emitResponse (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/index.js:659:20)
          at /home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/index.js:795:38
          at IncomingMessage.<anonymous> (/home/ec2-user/alihuda-proxy/node_modules/superagent/lib/node/parsers/json.js:16:7)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:80:11)
        status: 503,
        text: '{}',
        method: 'GET',
        path: '/analytics?type=video&video_id=225434&from=2018-01-16&by=day' },
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     type: 'application/json',
     setEncoding: [Function: bound ],
     redirects: [] },
  status: 503 }
```

**Comment by davegonzalez** [comment]
@jasenkoh thanks for the report! do you happen to have an example of how you're using the library? This is the first I've seen this error come up.
